import type { Metadata } from "next";
import { Noto_Sans } from 'next/font/google';
import "./globals.css";
import { Header } from "@/components/header";


// Configure the font
const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
  variable: '--font-noto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body
        className={`${notoSans.variable} antialiased dark`}
      >
        <Header />
        <main className="max-w-[1250px] m-auto">
          <div className="border-l border-r border-dashed mt-mobile-header md:mt-desktop-header px-5">
            <div className="pb-[1000px]">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
